<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web routes
|--------------------------------------------------------------------------
|
| app-user-dashboard · VM2 Application Server 1 · PHP 8.2 · port 8082
|
| Authentication (login, register, password reset, email verification) lives
| in routes/auth.php, generated by Laravel Breeze.
|
*/

// The dashboard is the whole point of the application: send visitors straight
// to it, or to the login screen if they are not signed in yet.
Route::get('/', function () {
    return redirect()->route(auth()->check() ? 'dashboard' : 'login');
});

Route::get('/dashboard', DashboardController::class)
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
| Health endpoint with the same contract as the other applications of the
| estate, so the Python monitoring utility treats all nine the same way.
*/
Route::get('/health', function () {
    return response()->json([
        'status' => 'ok',
        'application' => 'app-user-dashboard',
        'server' => 'VM2-Application-Server-1',
        'php' => PHP_VERSION,
        'laravel' => app()->version(),
        'environment' => app()->environment(),
        'checked_at' => now()->toIso8601String(),
    ]);
})->name('health');

require __DIR__.'/auth.php';
